spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/gamification
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:/db/changelog.xml

jwt.secret.key=aboba123
email.username=damirgarifullin7@gmail.com
email.password=czpd ppdt dtpf pmid
